name: Build and push to aws

on:
  push:
    branches:
      - feat/*
  pull_request:
    branches:
      - dev
      - main


jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'

    - name: Restore and Build
      run: |
          dotnet restore
          dotnet build --configuration Release

    - name: Run tests
      run: dotnet test --verbosity normal

    - name: Publish project
      run: dotnet publish ./EncryptoApi/EncryptoApi.csproj --configuration Release --output ./publish

    - name: Create zip package
      run: cd site; zip ../site.zip *;

    - name: Deploy to AWS EB
      uses: einaregilsson/beanstalk-deploy@v21
      with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: Chiffer API
          environment_name: ChifferAPI-env
          version_label: ${{ github.run_id }}
          region: eu-north-1
          deployment_package: site.zip